const productsData = [
  {
    id: 1,
    name: "Classic Aviator Sunglasses",
    price: 1599,
    oldPrice: 2999,
    rating: 5,
    reviews: 125,
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDhBzWEBmp83B4RzzAoPco0iM-KSSCO9vnSj0n3r45FrGGLzFg892hIKJ5OE1lW5n1zNC-dpcgX0-CwhugWHEIgn6264SyjsStAOtf1rphoTUdv2PLI4LQ7y4ri6aW35ui9JUbnPprPWcQfGyotS6LP1Z5zO4T-UnGJtNWFTnQEbh6F-Zpip7j1eM4KrvPQUmOC8we54gSE1-sN-cqaWyetkL027yl8vECOtRjsSUjZt-Q3l0osmimVBoea6uID2rCMX874mEoUoi8",
    badges: ["New", "-30%"],
    liked: false,
    brand: "RayBan",
    shape: "Aviator",
    colors: ["Gold", "Brown"],
    size: "Medium",
    material: "Metal",
    weight: "Light",
    rxType: "SingleVision",
    powers: ["-1.0", "-1.5"],
    width: 135,
    prodType: "Eyewear",
    collection: "Summer2025",
  },
  {
    id: 2,
    name: "Retro Square Sunglasses",
    price: 4500,
    oldPrice: null,
    rating: 5,
    reviews: 210,
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBlF8FC7nvDuvuhmV5zKpBc4cjhgOtcczSQKcwTb5wUqdOnWboR_X7NzenBx19JCSgjcAG0XZsaDmGLuUuWjbyV0VSvxRK4MGsLWRNMN3GslK4M7zrYtBY1qwQj5iejuj280sq94dQ-nQx-hQkRem24X_i-m7X_X7vAxCKBdiXr9azqvqk4SDmtTY5ziWm2VKIakEdb9j5GjDDMmHICjwLN9Lf-sCOjxwWmsVMaCQDXwpVyLZ1tR-gbZW5UDduFsSsEbv2ontnV1uY",
    badges: ["Best Seller"],
    liked: true,
    brand: "Gucci",
    shape: "Square",
    colors: ["Black"],
    size: "Large",
    material: "Acetate",
    weight: "Medium",
    rxType: "Progressive",
    powers: ["-2.0"],
    width: 142,
    prodType: "Eyewear",
    collection: "Classic",
  },
  {
    id: 3,
    name: "Sporty Wrap-Around Sunglasses",
    price: 3550,
    oldPrice: null,
    rating: 4,
    reviews: 88,
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuAyR0EMHHMPCpu8SIVeLEyF6aF4e7iUen938T1BNwE9hb-A0LAFHPGXs81Ml9k1vw4xPfREq0-tUK6Sr_KiLRvUdw6gdBU_qKI1pdxaLNHBwQUdpD5XP5x1km8sgY3YdjYiAACSG1uyoxTUX8AhHIIZ6O3E-MrSoXn0l6ycheUXsBxj_z2Na_PfHylpuiaXDctlPiCYXgxoqknwtaM8paf8kCg8kL4JeB7L2ugAzmG6mEyFiAT-flzm667bqsxOfgizBn0au37NpII",
    badges: [],
    liked: false,
    brand: "Oakley",
    shape: "Wrap",
    colors: ["Blue", "Black"],
    size: "Medium",
    material: "Plastic",
    weight: "Light",
    rxType: "SingleVision",
    powers: ["-1.5"],
    width: 140,
    prodType: "Eyewear",
    collection: "Sports",
  },
  {
    id: 4,
    name: "Elegant Cat-Eye Sunglasses",
    price: 1200,
    oldPrice: null,
    rating: 5,
    reviews: 150,
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuCxVKzZPhNYW6K_wNFiP-EEYnN0qkx4Et8h3aBksDThRbkCmIoLQHiJrzoOQg1JYFyAyelFgy2ScbLt6RLoVgMymhPjzfoRv87ZFfE_ZTjQ4TwDAfS7A7CjFW_IPcO72FWXDsaifv4MSB_z9YXerorm0OOpXsi44CLWZOM5vBQhwMrRXdl4RgyHKN7j4culoI0AxoadPwf78Q5tjQJ8vXarVyhHOeIryUgsuILoMdxbrJrfyO35dhkLVb1388-xqmoy3CGtA9b-KJ0",
    badges: [],
    liked: false,
    brand: "Prada",
    shape: "CatEye",
    colors: ["Red", "Gold"],
    size: "Small",
    material: "Acetate",
    weight: "Light",
    rxType: "SingleVision",
    powers: ["-1.25"],
    width: 130,
    prodType: "Eyewear",
    collection: "Luxury",
  },
  {
    id: 5,
    name: "Modern Geometric Sunglasses",
    price: 2500,
    oldPrice: null,
    rating: 5,
    reviews: 300,
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBVmutmBxSbcyqU38HzHO8-BLykmb3vaCUbDjTN_JowqetHZm8yT1YYAVmsB72qgv_1EMOtJ2dPT6NnqPxd3nzqXz2WKYI7C2hmptX6ZrnVkIivlwKT9BqZo8wTSubkW2QqSiyVmFQkZnSJBFY-LxSJSY45Q9OViOe5JhojiRDPX5QrbwOfybFnlUGbC1VH6zj4_VsBMhpp8mt-DmITevTFnTvqaMqsLRm1IWRqz3rVGeCnSG4DWXcMfL8JCRlVfONc4wMkeJa1mGA",
    badges: [],
    liked: true,
    brand: "Versace",
    shape: "Geometric",
    colors: ["Silver", "Gray"],
    size: "Medium",
    material: "Metal",
    weight: "Medium",
    rxType: "SingleVision",
    powers: ["-2.0"],
    width: 138,
    prodType: "Eyewear",
    collection: "Trendy",
  },
  {
    id: 6,
    name: "Minimalist Round Sunglasses",
    price: 5500,
    oldPrice: null,
    rating: 4,
    reviews: 95,
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuDz9WHYLAEc4muKcttUKDu2DBlCrmtZHKCnT6B7YY8ew4llZC8Pooi7IWaQ-UPELlS1uISXxPH9PhSqbh8cw3JcpIeHEVvOpPzEI7Kq0KuUSLWOLKRv299wy-vIqmUC2OAY58XykPXM3C3HUYQwJBVh3VV7DG8bW3RFmQxfYjZ2JUtRDZ0S0KXprYH-OIuJz8zv0q2bbw0mt06wCyzfHKuf9s5ycnYYkhEYCMeWUJIGCXXzFLmdxIrJDC_YVytQ4Sy-YoTR9Vh1G20",
    badges: [],
    liked: false,
    brand: "Chanel",
    shape: "Round",
    colors: ["Black", "Silver"],
    size: "Small",
    material: "Metal",
    weight: "Light",
    rxType: "Progressive",
    powers: ["-2.25"],
    width: 128,
    prodType: "Eyewear",
    collection: "Luxury",
  },
  {
    id: 7,
    name: "Bold Oversized Sunglasses",
    price: 1500,
    oldPrice: 1800,
    rating: 5,
    reviews: 75,
    image:
      "https://lh3.googleusercontent.com/aida-public/AB6AXuBh7_C_aGoqz7vWPyB1Bvx6clbmR-75-DEH6GTiWq9Uw1lLlUzYTn9s9XLBlhw1eO37Wjdz4arvRyAVGWZfZV5AddeH8ogBZvQOGef-9el3nPI7TZ6z_z2kg71m_pY7eA44MNjhkYeGMjDY-hg_qnoBb8mPfmOcFRuBsLP1w6zHjNUeagosDCLO_uzqedhMSH4MvAQeIVV9lwxPAPg9q1kYwVvd57QgrDWMVgsZhbDFWER1Lxg95q5RhQ5vx_rXN7YqmbifUPe86mA",
    badges: ["Sale"],
    liked: false,
    brand: "Dior",
    shape: "Oversized",
    colors: ["Black"],
    size: "Large",
    material: "Acetate",
    weight: "Heavy",
    rxType: "SingleVision",
    powers: ["-3.0"],
    width: 150,
    prodType: "Eyewear",
    collection: "Bold",
  },
  {
    id: 8,
    name: "Classic Aviator Sunglasses",
    price: 1499,
    brand: "RayBan",
    type: "Sunglasses",
    shape: "Aviator",
    colors: ["Gold", "Brown"],
    size: "Medium",
    material: "Metal",
    weight: "Light",
    rxType: "Non-Rx",
    powers: "NA",
    width: 140,
    prodType: "Eyewear",
    collection: "Summer",
    image:
      "https://www.voyageeyewear.com/cdn/shop/files/2_2d7a94d1-ef5b-4e51-81f2-2e829f15f5e4.jpg?v=1714424530&width=2500",
    liked: false,
  },
  {
    id: 9,
    name: "Square Full-Rim Glasses",
    price: 999,
    brand: "Lenskart",
    type: "Eyeglasses",
    shape: "Square",
    colors: ["Black"],
    size: "Medium",
    material: "Acetate",
    weight: "Medium",
    rxType: "Single Vision",
    powers: "0 to -5",
    width: 138,
    prodType: "Eyewear",
    collection: "Everyday",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTj8mjTh0s21t8Xx17N3AVs6NXzzEZ8XUt2oQ&s",
    liked: false,
  },
  {
    id: 10,
    name: "Round Blue Light Blockers",
    price: 1299,
    brand: "Nazario",
    type: "Eyeglasses",
    shape: "Round",
    colors: ["Blue", "Transparent"],
    size: "Small",
    material: "TR90",
    weight: "Light",
    rxType: "Blue Light",
    powers: "0 to -3",
    width: 135,
    prodType: "Eyewear",
    collection: "Digital",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdtz0cygo9SpgxAm9R2aLiI_Ol-UosFl0e6g&s",
    liked: false,
  },
  {
    id: 11,
    name: "Sporty Wrap Sunglasses",
    price: 1899,
    brand: "Oakley",
    type: "Sunglasses",
    shape: "Wrap",
    colors: ["Black", "Red"],
    size: "Large",
    material: "Polycarbonate",
    weight: "Medium",
    rxType: "Non-Rx",
    powers: "NA",
    width: 145,
    prodType: "Eyewear",
    collection: "Sports",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5RZXFGTjLQXNQcRWx4nLDsLWP7gOFoiFSWw&s",
    liked: false,
  },
  {
    id: 12,
    name: "Cat-Eye Fashion Glasses",
    price: 1599,
    brand: "Vogue",
    type: "Eyeglasses",
    shape: "Cat-Eye",
    colors: ["Pink", "Gold"],
    size: "Small",
    material: "Acetate",
    weight: "Light",
    rxType: "Single Vision",
    powers: "0 to -4",
    width: 132,
    prodType: "Eyewear",
    collection: "Trendy",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGYqnHKJBaa7B7WsPlPdaOdO0j1JDOnREsvw&s",
    liked: false,
  },
  {
    id: 13,
    name: "Rectangle Professional Glasses",
    price: 1199,
    brand: "Titan",
    type: "Eyeglasses",
    shape: "Rectangle",
    colors: ["Brown"],
    size: "Medium",
    material: "Metal",
    weight: "Medium",
    rxType: "Bifocal",
    powers: "0 to -6",
    width: 139,
    prodType: "Eyewear",
    collection: "Office",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpZgswB-X8zXHqKXLvLI4ITyInbcJETzjn0w&s",
    liked: false,
  },
  {
    id: 14,
    name: "Oversized Glam Sunglasses",
    price: 2499,
    brand: "Gucci",
    type: "Sunglasses",
    shape: "Oversized",
    colors: ["Black", "Gold"],
    size: "Large",
    material: "Acetate",
    weight: "Heavy",
    rxType: "Non-Rx",
    powers: "NA",
    width: 150,
    prodType: "Eyewear",
    collection: "Luxury",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8PillHi3ydrIY6_Z0876NDeYUbuDnJCeysw&s",
    liked: false,
  },
  {
    id: 15,
    name: "Rimless Lightweight Glasses",
    price: 1799,
    brand: "Nazario",
    type: "Eyeglasses",
    shape: "Rimless",
    colors: ["Silver"],
    size: "Medium",
    material: "Titanium",
    weight: "Ultra-Light",
    rxType: "Progressive",
    powers: "0 to -8",
    width: 137,
    prodType: "Eyewear",
    collection: "Minimalist",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQu76RElY_wW4QqDAYcoii3iYzo4xEwlYCFFA&s",
    liked: false,
  },
];

export default productsData;
